name: YNOV pipeline CI/CD

on: [push, workflow_dispatch] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          pip install bottle

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Lint with black
        run: |
          black . --check

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with Pytest
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: MEP
        run: echo "MEP on server"

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Test if website is up 🚀
        run: |
          pip install requests
          python -c "import requests; exit(1) if requests.get('https://www.google.fr').status_code != 200 else exit(0)"
  Reporting:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: deploy
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies
        run: |
        pip install pytest
        pip install pytest-cov
        
      - name: Slack message
        run: |
          echo Pepiline terminé !
          pytest --cov=. . --doctest-modules --cov-report html


