name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          
      - name : Checkout
        uses: actions/checkout@v3
        
      
      - name: Run Tests 
        run: |
          echo Lancement des tests flake8 :
          flake8 .
          black --check .
          echo Fin des tests flake8.
          
      - name: Lancement de l'app
        run: |
          py ./app.py
          curl http://localhost:8080/hello/testname



