name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        
      - name: Setup Flake8  
        uses: julianwachholz/flake8-action@v2.0.2
        with:
    # The name of the check to add annotations to. Generally the same as the job that uses this action
          checkName: app.py
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          Lancement des tests flake8 :
          /home/runner/.local/bin/flake8 app.py
          Fin des tests flake8.


