name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Lancement des tests flake8 :
          flake8 ./app.py 
          echo Fin des tests flake8.



